#!/bin/sh
while read file
do
	case "$1" in
		"y")
			echo -n "$file" | xclip -selection clipboard ;;
		"w")
			ln -sf "$file" $HOME/.config/wall && xwallpaper --zoom "$HOME/.config/wall" ;;
	esac
done
